.github/workflows/scriptanalyzer.yml
changelog.txt
src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1909.ps1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.psd1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.schema.psm1

- Generated resource based on benchmark version 1.8.1 for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/3
- Included example usage
- Attached CIS-CAT results. Verified 1.1.5 and 2.3.10.1 failing where false positives from CIS-CAT. (Changed from .HTML to .TXT so I could post here)
[CIS-Win10-1909-CIS_Microsoft_Windows_10_Enterprise_Release_1909_Benchmark-20200814T103119Z.txt](https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/files/5077089/CIS-Win10-1909-CIS_Microsoft_Windows_10_Enterprise_Release_1909_Benchmark-20200814T103119Z.txt)
- Adjusted ScriptAnalyzer action to resolve errors with DSC resource parsing

Added resource for Windows 10 Enterprise Build 1909

---

.github/workflows/PublishToGallery.ps1
.github/workflows/pr_reminder.yml
.github/workflows/publishtogallery.yml

- Added publish action to automate publishing to the PSGallery
- Attempted to fix PR reminder action
- Generated a package specific publish key for this on PSGallery and added it as a repo secret

Release + PR actions

---

src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1909.ps1

- Made a more complete example of CIS_Microsoft_Windows_10_Enterprise_Release_1909
- Removed gitkeep now that stuff is in that folder

Example tweaks

---

.gitignore
src/CISDSCResourceGeneration/CISDSCResourceGeneration.psm1
src/CISDSCResourceGeneration/functions/private/ConvertFrom-AuditPolicySubcategoryRawGPO.ps1
src/CISDSCResourceGeneration/functions/private/ConvertFrom-PrivilegeRightRawGPO.ps1
src/CISDSCResourceGeneration/functions/private/ConvertFrom-RegistryPolGPORaw.ps1
src/CISDSCResourceGeneration/functions/private/ConvertFrom-RegistryValueRawGPO.ps1
src/CISDSCResourceGeneration/functions/private/ConvertFrom-ServiceRawGPO.ps1
src/CISDSCResourceGeneration/functions/private/ConvertFrom-SystemAccessRawGPO.ps1
src/CISDSCResourceGeneration/functions/private/Export-RecommendationErrors.ps1
src/CISDSCResourceGeneration/functions/private/Get-RecommendationFromGPOHash.ps1
src/CISDSCResourceGeneration/functions/private/Import-AudicCsv.ps1
src/CISDSCResourceGeneration/functions/private/Import-GptTmpl.ps1
src/CISDSCResourceGeneration/functions/private/Import-RegistryPol.ps1
src/CISDSCResourceGeneration/functions/public/ConvertTo-DSC.ps1
test/CISDSCResourceGeneration.Tests.ps1

- Built the functionality of the [ScaffoldingBlock] class into the [Recommendation] class. There was a lot of duplicate parameters between these two and while they were separate some of the below enhancements were impossible without a lot of inefficient code. There are several files impacted by this refactor but all major refactoring was done src/CISDSCResourceGeneration/CISDSCResourceGeneration.psm1 the rest is just resulting changes to account for these.
- More efficient detection of recommendation errors
- Various small improvements
- Added logic to help detect the appropriate setting in a recommendation is parameterized instead of all of them.
- If a recommendation contains multiple settings it will now be bundled inside the same IF statement of the resource instead of separate …

Refactor to address various issues

---

.github/workflows/pester.yml
.github/workflows/scriptanalyzer.yml

Adjusted the "on" statement to only run style checks and unit tests when the actual code changes

scoped actions to src

---

src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.psd1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.schema.psm1
static_corrections/Win10_1909_corrections.csv

- Regenerated the Win 10 1909 resource to take advantage of the enhancements in the generation module
- Verified the following are false positives failures from CIS-CAT attached HTML report (renamed to txt to attach)
[CIS-Win10-1909-CIS_Microsoft_Windows_10_Enterprise_Release_1909_Benchmark-20200910T081727Z.txt](https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/files/5202862/CIS-Win10-1909-CIS_Microsoft_Windows_10_Enterprise_Release_1909_Benchmark-20200910T081727Z.txt)
- 1.1.5
- 2.3.1.1 (doesn't work with LAPS)
- 2.3.10.1
-5.* (services that failed don't exist)
- 18.4.10
-19.* (N/A user settings)

1909 remix

---

src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1809_With_LAPS.ps1
src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1909_With_LAPS.ps1

- Added alternate examples that will install also LAPS directly from Microsoft

Added examples with a LAPS install

---

src/CISDSCResourceGeneration/CISDSCResourceGeneration.psm1

- short and sweet solution for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/97

Added support for no default value exceptions

---

.github/workflows/pester.yml
.github/workflows/scriptanalyzer.yml
src/CISDSC/CISDSC.psd1
src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1

- Solution for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/101
- Actions updated
- Module manifests updated
- Branch protection policy and default branch have been updated on the repository settings (please double check me!)

Rename of primary branch to "main"

---

.github/workflows/PublishToGallery.ps1

There is apparently a bug with PSDepend on ubuntu so I've made the installs explicit in the deployment script. Should resolve the below.
https://user-images.githubusercontent.com/28571284/93488056-8dd7c880-f8cb-11ea-985a-09ac5e1faad9.png

made installs explicit

---

README.md

- Added video credit
- Updated install instructions to reference the PSgallery page

updated install instructions

---

README.md
docs/notification.md

- Fleshed out notification document
- Updated Readme to reference previously merged contributions doc as well as put the notification information in a more intuitive place.

Readme and Notifications

---

src/CISDSCResourceGeneration/functions/private/Get-ApplicableLevels.ps1
src/CISDSCResourceGeneration/functions/private/Get-DSCDocumentationPropertyTable.ps1
src/CISDSCResourceGeneration/functions/private/Get-DSCDocumentationSyntax.ps1

Solution for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/118

Added missing comment based help

---

CHANGELOG_CISDSCResourceGeneration.md
src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1
src/CISDSCResourceGeneration/CISDSCResourceGeneration.psm1
src/CISDSCResourceGeneration/functions/private/Import-CISBenchmarkData.ps1
src/CISDSCResourceGeneration/functions/public/ConvertTo-DSC.ps1
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/plasterManifest.xml
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/resource.schema.psm1.plaster
test/CISDSCResourceGeneration.Tests.ps1

- Solution for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/129

Removed hard coded recommendation IDs

---

CHANGELOG_CISDSCResourceGeneration.md
src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1
src/CISDSCResourceGeneration/CISDSCResourceGeneration.psm1
src/CISDSCResourceGeneration/functions/private/Import-AudicCsv.ps1
src/CISDSCResourceGeneration/functions/private/Import-GptTmpl.ps1
src/CISDSCResourceGeneration/functions/private/Import-ParameterOverrides.ps1
src/CISDSCResourceGeneration/functions/private/Import-RegistryPol.ps1
src/CISDSCResourceGeneration/functions/public/ConvertTo-DSC.ps1
test/CISDSCResourceGeneration.Tests.ps1
test/example_files/parameter_overrides.csv

- Solution for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/71
- Opted to use a new CSV for this enhancement vs past me's suggestion of the existing static corrections. This is because there is a lot of functionality tied to that import and I'd rather not introduce new bugs by changing it.
- Few new unrelated verbose statements to assist with troubleshooting new resources.

Added override support for DSC parameters

---

CHANGELOG.md
parameter_validations/Win10_1809_validations.csv
parameter_validations/Win10_1909_validations.csv
parameter_validations/Win10_2004_validations.csv
src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_1809.md
src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_1909.md
src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_2004.md
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.psd1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.schema.psm1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.psd1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.schema.psm1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_2004/CIS_Microsoft_Windows_10_Enterprise_Release_2004.psd1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_2004/CIS_Microsoft_Windows_10_Enterprise_Release_2004.schema.psm1

- Fixed existing resources per https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/136
- A separate branch/PR will be created to fix this in the generation module

Issue136 retroactive correction

---

CHANGELOG.md
parameter_validations/Win10_1809_validations.csv
parameter_validations/Win10_1909_validations.csv
parameter_validations/Win10_2004_validations.csv
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.psd1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.schema.psm1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.psd1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.schema.psm1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_2004/CIS_Microsoft_Windows_10_Enterprise_Release_2004.psd1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_2004/CIS_Microsoft_Windows_10_Enterprise_Release_2004.schema.psm1
test/example_files/parameter_validations.csv

- Solution for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/135
- Updated effected resources and validation CSVs. There were no changes required in the documentation files for this.

Corrected parameter validation

---

src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_1809.md
src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_1909.md
src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_2004.md
src/CISDSC/docs/CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607.md
src/CISDSC/docs/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_1809.md
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/resource.documentation.md

- It was the only same line curly in the docs so I made it uniform in existing docs and plaster

Fixed out of place curly in examples

---

README.md
docs/new_resources.md
docs/notification.md
test_machine_setup.ps1

- Added a script to facilitate getting a VM ready to test a generated resource on.
- Added a link to saltstack DSC documentation

Added script for setting up a new test machine

---

.github/workflows/pester_CISDSC.yml
.github/workflows/pester_CISDSCResourceGeneration.yml
.github/workflows/publishtogallery.yml
.github/workflows/scriptanalyzer.yml

Using the latest version of the checkout action per GitHub support for #154

bumped actions up to actions/checkout@v2

---

CHANGELOG.md
src/CISDSC/CISDSC.psd1

- Bumped module version
- Cleaned up changelog language

v2.0.1 release

---

CHANGELOG.md
src/CISDSC/CISDSC.psd1

- finalized change log
- bumped version number in manifest

V2.1.0 prep

---

CHANGELOG_CISDSCResourceGeneration.md
src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1
src/CISDSCResourceGeneration/CISDSCResourceGeneration.psm1
src/CISDSCResourceGeneration/functions/private/Get-DSCDocumentationSyntax.ps1
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/example.ps1.plaster
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/example_With_LAPS.ps1.plaster
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/resource.documentation.md
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/resource.schema.psm1.plaster
test/CISDSCResourceGeneration.Tests.ps1

Aims to resolve the generation half of #169 
- Prefixes all parameters with an "a" in the resource schemas as well as documentation
- Corrects all instances of ExclusionList with ExcludeList

Issue169 Part 2

---

CHANGELOG_CISDSCResourceGeneration.md
src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/example.ps1.plaster
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/example_With_LAPS.ps1.plaster
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/resource.documentation.md
src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/resource.schema.psm1.plaster

Looks like I fudged a global find/replace in #171 this should fix the plaster templates

plaster fixes

---

CHANGELOG.md
src/CISDSC/CISDSC.psd1

Version bump and changelog update for new release

v2.2.0 release

---

src/CISDSCResourceGeneration/plasterTemplates/NewBrowserBenchmarkCompositeResource/example.ps1.plaster

- Removed duplicate import line in the plaster template that the linter found on #191

removed extra line

---

README.md
docs/contribution.md
docs/design_choices.md
docs/new_resources.md

- Added disclaimer about composite resource support in various platforms
- Added support statement
- Added missing example for creating a browser benchmark
- Added design choices document to explain some of the less obvious decisions

Documentation

---

README.md
SECURITY.md

Last missing documents for github community standards checklist
#198

Security document and README tweaks

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

Created issue templates with the github GUI

Update issue templates

---

README.md

_Describe the problem or feature in addition to a link to the issues._ Added warning about applying benchmarks to unsupported workgroup systems.
_How does this change address the problem?_ It warns the user.
#210

Workgroup notice

---

CHANGELOG.md
src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_21H1.ps1
src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_21H1_With_LAPS.ps1
src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_21H1.md
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_21H1/CIS_Microsoft_Windows_10_Enterprise_Release_21H1.psd1
src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_21H1/CIS_Microsoft_Windows_10_Enterprise_Release_21H1.schema.psm1

_Describe the problem or feature in addition to a link to the issues._ Add support for Windows 10 21H1 #208 
_How does this change address the problem?_ Resource was generated with the generation module and the required corrections documented in #212

21h1 resource

---

CONTRIBUTING.md
docs/design_choices.md

_Describe the problem or feature in addition to a link to the issues._ Reflect the new policy on CIS-CAT scans after an internal conversation. Also added a note about legacy benchmark formatting support.
_How does this change address the problem?_ This new process will decrease the effort required to release resources for new benchmark versions

CIS-CAT scan policy change

---

CHANGELOG.md
src/CISDSC/CISDSC.psd1

_Describe the problem or feature in addition to a link to the issues._ Stage a release for v2.5.0 to publish the addition of the Windows 10 21H1 resource.
_How does this change address the problem?_ Changelog and manifest edits are finalized so a release can be tagged

v2.5.0 release

---

src/CISDSC/CISDSC.psd1

_Describe the problem or feature in addition to a link to the issues._ there was a bad uri
_How does this change address the problem?_ fixed the uri with a raw flag in the uri.

fixed icon

---

CHANGELOG_CISDSCResourceGeneration.md
src/CISDSCResourceGeneration/functions/private/Export-MissingRecommendations.ps1
src/CISDSCResourceGeneration/functions/private/Export-RecommendationErrors.ps1
src/CISDSCResourceGeneration/functions/private/Get-ApplicableLevels.ps1
src/CISDSCResourceGeneration/functions/private/Get-CISBenchmarkValidWorksheets.ps1
src/CISDSCResourceGeneration/functions/private/Get-DSCParameterTextBlocks.ps1
src/CISDSCResourceGeneration/functions/private/Import-ParameterOverrides.ps1
src/CISDSCResourceGeneration/functions/private/Import-ParameterValidations.ps1
src/CISDSCResourceGeneration/functions/private/Import-StaticCorrections.ps1
src/CISDSCResourceGeneration/functions/private/Resolve-RegistryValueSpecialCases.ps1

_Describe the problem or feature in addition to a link to the issues._ resolve issues with the new scriptanalyzer plural nouns rule
_How does this change address the problem?_ Added the exception where applicable.

Scriptanalyzer

---

CHANGELOG_CISDSCResourceGeneration.md
src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1
src/CISDSCResourceGeneration/functions/private/Get-RecommendationFromGPOHash.ps1

_Describe the problem or feature in addition to a link to the issues._ Resolves #225
_How does this change address the problem?_ Adds the missing wildcard and removes redundant variable assignment.

Issue225 fix

---

docs/new_resources.md

_Describe the problem or feature in addition to a link to the issues._ typo
_How does this change address the problem?_ fixed the typo

Typo from #229

---

CHANGELOG.md
src/CISDSC/CISDSC.psd1

_Describe the problem or feature in addition to a link to the issues._ Raw links are more easily integrated into third party sites such as the PSGallery
_How does this change address the problem?_ Added the raw flag to the URIs.

Corrected URIs in module manifest

---

docs/static_corrections.md

Yes.
Fixes #255
Text replacement.

Additional URL fix

---

CHANGELOG_CISDSCResourceGeneration.md
src/CISDSCResourceGeneration/functions/public/ConvertTo-DSC.ps1
tools/find_changed_recommendations.ps1

_Describe the problem or feature in addition to a link to the issues._ CIS hasn't yet mastered the art of consistency so "find_changed_recommendations.ps1" has been updated with the "forkCSVs" flag to generate updated CSVs with the IDs corrected where changed. They refuse to change this behavior and there was >100 changes in the latest benchmarks. /rant
Also part of #252 
_How does this change address the problem?_ It's a glorified find/replace that will tell you when it needs manual review

Tooling enhancements

---

CHANGELOG.md
src/CISDSCResourceGeneration/functions/private/Get-RecommendationFromGPOHash.ps1

Fix for NUL character in registry policy file

---

.github/workflows/pr_reminder.yml

_Where the guidelines in [CONTRIBUTING.md](/CONTRIBUTING.md) followed?_
_Describe the problem or feature in addition to a link to the issues._
_How does this change address the problem?_

Add user map to pull requests

---

CHANGELOG.md
CHANGELOG_CISDSCResourceGeneration.md
src/CISDSC/docs/CIS_Microsoft_Windows_11_Enterprise_Release_23H2.md
src/CISDSC/dscresources/CIS_Microsoft_Windows_11_Enterprise_Release_23H2/CIS_Microsoft_Windows_11_Enterprise_Release_23H2.psd1
src/CISDSC/dscresources/CIS_Microsoft_Windows_11_Enterprise_Release_23H2/CIS_Microsoft_Windows_11_Enterprise_Release_23H2.schema.psm1
src/CISDSC/examples/CIS_Microsoft_Windows_11_Enterprise_Release_23H2.ps1
src/CISDSC/examples/CIS_Microsoft_Windows_11_Enterprise_Release_23H2_With_LAPS.ps1

- Windows 11 23H2 Resources, documentation and example scripts

Add win 11 resource

---

.github/workflows/cleanup.yml

Create `cleanup.yml` to Add Stale Issue Automation for `SecOps-Powershell-CISDSC`

---

CHANGELOG.md
src/CISDSC/dscresources/CIS_Microsoft_Windows_11_Enterprise_Release_23H2/CIS_Microsoft_Windows_11_Enterprise_Release_23H2.schema.psm1

Fix issues from the recommendation 5.3 in Win 11 23H2.
Remove recommendation 5.3 from Win 11 23H2.
Closes #276

Remove 5.3

---

CHANGELOG.md
src/CISDSC/CISDSC.psd1

First release including the Win 11 23H2 resource.

Release 4.0.0
