src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.schema.psm1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.schema.psm1
18910212BranchReadinessLevel & 18910212DeferFeatureUpdates where incorrectly assigned parameters because they are associated with 18910212DeferFeatureUpdatesPeriodInDays which should have a parameter.
18941AllowSharedLocalAppData was incorrectly given a parameter due to the "between" in "(L2) Ensure Allow a Windows app to share application data between users is set to Disabled"
=> removed false parameters

src/CISDSCResourceGeneration/CISDSCResourceGeneration.psm1, src/CISDSCResourceGeneration/functions/private/Resolve-RegistryValueSpecialCases.ps1
- Commented out "between" being a keyword for a parameter as this was causing false positives.
- Added 2 registry special cases that were repeat offenders of an encoding issue.
=> Small bug fixes

src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.schema.psm1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.schema.psm1, src/CISDSCResourceGeneration/functions/private/Resolve-RegistryValueSpecialCases.ps1
- $111Enforcepasswordhistory and $114MinimumPasswordLength were removed because their minimum values per the benchmark are actually the maximum supported for the settings themselves meaning no supported values other than the default would be functional and compliant.
- Added validation blocks for every parameter after reviewing MS documentation for the values
- Added a registry special case for ScreenSaverGracePeriod as it was being picked up as a string from registry.pol but is actually a dword/int value
- $2377CachedLogonsCount is intentionally a validate set and not a range since MS made this a string for some reason.
=> Parameter audit

src/CISDSCResourceGeneration/functions/private/ConvertFrom-RegistryPolGPORaw.ps1, src/CISDSCResourceGeneration/functions/private/ConvertFrom-RegistryValueRawGPO.ps1, src/CISDSCResourceGeneration/functions/private/Resolve-RegistryValueSpecialCases.ps1
- Solution for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/74
- The special cases situation was N/A for ConvertFrom-RegistryValueRawGPO
- Removed the legal text special case as that setting has been working fine while this function was broken. This was a carry over from the baseline management module this was forked from
- Corrected values for existing special cases
=> Issue74 solution

src/CISDSCResourceGeneration/functions/private/ConvertFrom-RegistryValueRawGPO.ps1, src/CISDSCResourceGeneration/functions/private/Resolve-RegistryValueSpecialCases.ps1
This was incorrectly removed in a previous PR and was causing this to create a string array parameter vs a string.
=> Added registry special case for LegalNoticeText

src/CISDSCResourceGeneration/CISDSCResourceGeneration.psm1, test/CISDSCResourceGeneration.Tests.ps1
The previous refactor changed the logic in which resource titles are de-duplicated which is a requirement for DSC. This introduced a bug for duplicate titles in separate recommendations which is rare but happens. See below example where the same title is used to describe a client setting and a server setting for WinRM. This change will prefix the title with the recommendation number to ensure this does not happen.
=> altered DSCtitle logic

src/CISDSCResourceGeneration/functions/private/Get-RecommendationFromGPOHash.ps1
- Small enhancement to also check the "remediation procedure" for the registry key when linking GPO to CIS recommendation
- Solution for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/93
=> Added an extra check for the remediation procedure

src/CISDSCResourceGeneration/functions/private/Export-RecommendationErrors.ps1
- Small formatting tweak to make the exported recommendation errors more human readable as this file is only ever ingested by humans. Now there is a dividing line separating the errors found.
=> adjusted formatting for error export

CHANGELOG.md, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.psd1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.schema.psm1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.psd1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.schema.psm1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_2004/CIS_Microsoft_Windows_10_Enterprise_Release_2004.psd1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_2004/CIS_Microsoft_Windows_10_Enterprise_Release_2004.schema.psm1, static_corrections/Win10_1809_corrections.csv, static_corrections/Win10_1909_corrections.csv, static_corrections/Win10_2004_corrections.csv
- This key was reconfigured due to some weirdness in the Registry.pol file it was generated from. This came to my attention after CIS responded to my ticket on it. The GPO was wanting to delete all values then populated them which lead to some conflicting values being set in some resources and being place in the wrong recommendation for them all.
=> Corrected recommendation ID

CHANGELOG.md, parameter_validations/Win10_2004_validations.csv, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_2004/CIS_Microsoft_Windows_10_Enterprise_Release_2004.schema.psm1
Password length was previously capped at 14 characters making this parameter useless, however with build 2004 this was changed. As long as 'Relax minimum password length limits' is enabled (which is recommendation 1.1.6) this setting now supports up to 128 characters.
https://www.bleepingcomputer.com/news/microsoft/windows-10-version-2004-adds-new-account-password-policies/
=> Fixed password length parameter

CHANGELOG.md, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_2004/CIS_Microsoft_Windows_10_Enterprise_Release_2004.schema.psm1, static_corrections/Win10_2004_corrections.csv
- Added missing key for HKLM:\SOFTWARE\Policies\Microsoft\AppHVSI:AppHVSIClipboardFileType to Windows 10 Enterprise 2004 18.9.46.5
=> AppHVSIClipboardFileType correction

CHANGELOG.md, src/CISDSC/CISDSC.psd1, src/CISDSC/CISDSC.psm1, src/CISDSC/docs/CISService.md, test/CISDSC.Tests.ps1, test/New-PSClassInstance.ps1
- First PR for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/121
- This resource is used to more accurately reflect the spirit of the CIS benchmarks for services. The recommendations are considered passed if the service is disabled or absent and this is not possible with the standard service resource.
- Subsequent PRs will update existing composite resources to use this as well as updates to the generation module to use it in new resources.
=> Added CISService resource

.github/workflows/scriptanalyzer.yml, CHANGELOG.md, src/CISDSC/CISDSC.psm1, src/CISDSC/Examples/CISService.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1809.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1809_With_LAPS.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1909.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1909_With_LAPS.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_2004.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_2004_With_LAPS.ps1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.psd1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.schema.psm1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.psd1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1909/CIS_Microsoft_Windows_10_Enterprise_Release_1909.schema.psm1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_2004/CIS_Microsoft_Windows_10_Enterprise_Release_2004.psd1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_2004/CIS_Microsoft_Windows_10_Enterprise_Release_2004.schema.psm1
- Corrected small typo in CISService comments
- Updated existing resources and examples for the CISService changes
- Continued work for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/121
- ScriptAnalyzer action was adjusted to look at the entire CISDSC module. The rule 'PSDSCDscTestsPresent' was excluded since this doesn't appear to like where the test folder is located at. There are indeed tests for this resource in the tests directory of this repo. It also now copies to the modules dir to satisfy some weird DSC behavior with detecting installed modules
=> Cis service

CHANGELOG_CISDSCResourceGeneration.md, src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1, src/CISDSCResourceGeneration/functions/private/ConvertFrom-ServiceRawGPO.ps1, src/CISDSCResourceGeneration/functions/private/Import-GptTmpl.ps1, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/resource.schema.psm1.plaster, test/CISDSCResourceGeneration.Tests.ps1
- service resource related functions where adapted to use the new resource. Service data was removed from ConvertFrom-ServiceRawGPO as this was an artifact of forking the baseline management module. CIS only recommends disabling services so we don't need to worry about translating the value. These were being inaccurately translated anyways.
- pester tests where updated to reflect new expectations of the functions
- part 3 for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/121
=> Cis service generation

CHANGELOG.md, src/CISDSC/CISDSC.psd1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.psd1, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_1809/CIS_Microsoft_Windows_10_Enterprise_Release_1809.schema.psm1, static_corrections/Win10_1809_corrections.csv
- Bumped manifest version
- Finalized changelog wording
- Deemed worthy of a minor release bump since this adds new functionality
- Removed duplicate key from Win10 1809 this somehow ended up in two recommendations when generated. Didn't appear present in later builds.
=> v1.1.0 release

.github/workflows/pester_CISDSC.yml, .github/workflows/pester_CISDSCResourceGeneration.yml, README.md
- Split unit test actions up for the two modules. This way tests will only run when relevant files are changed.
- CISDSC tests are scoped explicitly to the PSM1 file since this is the only file with non-generated code in it and the others change often.
- Updated badges in the README
=> Optimized pester actions

CHANGELOG_CISDSCResourceGeneration.md, src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1, src/CISDSCResourceGeneration/functions/private/Resolve-RegistryValueSpecialCases.ps1, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/example.ps1.plaster, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/example_With_LAPS.ps1.plaster, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/plasterManifest.xml, test/CISDSCResourceGeneration.Tests.ps1
- Solution for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/133
- Solution for https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/136
- The example files packaged with the module were being created by hand due to needing custom exclusion lists previously. This is no longer the case so they have been added as file templates to Plaster.
=> Added bundled resource examples to the Plaster template and bugfix

CHANGELOG_CISDSCResourceGeneration.md, src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1, src/CISDSCResourceGeneration/CISDSCResourceGeneration.psm1, src/CISDSCResourceGeneration/functions/private/Get-DSCParameterTextBlocks.ps1, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/resource.documentation.md
- Solution for #143 
- The dynamically generated types where camel cased while the statically typed ones were all lower case. I updated the static ones to be camel as well.
- Corrected plaster template for resource documentation to use the dynamic recommendation IDs from [Issue 129](https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/129)
=> Standardized casing

CHANGELOG.md, src/CISDSC/CISDSC.psd1
- Cleaned up changelog language and bumped manifest version for release.
- Conditions for the [v2 milestone](https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/milestone/2) have been met in #149 and #145
=> Housekeeping for v2.0.0 release

CHANGELOG.md, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1809.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1809_With_LAPS.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1909.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_1909_With_LAPS.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_2004.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_2004_With_LAPS.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607_With_LAPS.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_1809.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_1809_With_LAPS.ps1, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/example.ps1.plaster, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/example_With_LAPS.ps1.plaster
- All the examples require admin rights to work so I added the requirements flag to the scripts.
- Plaster templates were updated so this would be reflected on future examples.
=> Added RunAsAdministrator requirement to packaged examples

src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_2004.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_10_Enterprise_Release_2004_With_LAPS.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607_With_LAPS.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_1809.ps1, src/CISDSC/Examples/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_1809_With_LAPS.ps1, src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_1809.md, src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_1909.md, src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_2004.md, src/CISDSC/docs/CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607.md, src/CISDSC/docs/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_1809.md
- Retroactively applied fix for #159 that was added in #160 to remove underscores from various generated comments
- Fixed yet more inconsistent casing found in the Server 2016 documentation
=> #159 Retroactive

CHANGELOG_CISDSCResourceGeneration.md, src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1, src/CISDSCResourceGeneration/functions/public/ConvertTo-DSC.ps1, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/example.ps1.plaster, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/example_With_LAPS.ps1.plaster, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/manifest.psd1.plaster, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/plasterManifest.xml, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/resource.documentation.md, src/CISDSCResourceGeneration/plasterTemplates/NewBenchmarkCompositeResource/resource.schema.psm1.plaster, test/CISDSCResourceGeneration.Tests.ps1
- Solution for #159 
- Replaced existing references to the OS variable in plaster to OSWithUnderscores
- Updated pester test to say which file is missing vs just a file is missing on the ConvertTo-DSC test
- Corrected the applicable locations of the Plaster template to use the OS string without underscores
- A separate PR will retroactively apply this to existing examples and docs in #161
Before
After
=> #159 Generation

docs/auditing.md
-NoTypeInformation is needed for PowerShell 5.1 to make the CSV usable.
=> Added missing switch to example

.github/workflows/pester_CISDSC.yml, .github/workflows/pester_CISDSCResourceGeneration.yml, .vscode/tasks.json, CHANGELOG_CISDSCResourceGeneration.md, docs/new_resources.md, src/CISDSCResourceGeneration/CISDSCResourceGeneration.psd1, src/CISDSCResourceGeneration/functions/private/Import-RegistryPol.ps1, tools/install_dependencies.ps1
- Solution for #128 
- Latest version of GPRegistryPolicyParser included fixes for PS 7 support which unchains us from 5.1!
- Documentation, tools, and actions have been updated to reflect using PowerShell 7
- 'Prase-PolFile' was changed to 'Read-Polfile' since this was changed in GPRegistryPolicyParser to get rid of the unapproved verb warning at import
=> PowerShell 7 support - Issue128

CHANGELOG_CISDSCResourceGeneration.md, src/CISDSCResourceGeneration/functions/private/Get-CISBenchmarkValidWorksheets.ps1, src/CISDSCResourceGeneration/functions/private/Import-CISBenchmarkData.ps1, src/CISDSCResourceGeneration/functions/public/ConvertTo-DSC.ps1, test/CISDSCResourceGeneration.Tests.ps1
- Another piece of preparation for #184 
- 'OS' parameters on helper functions where renamed to 'System'
- Applicable pester tests updated to reflect the rename
- This will ultimately be called differently within ConvertTo-DSC but needs to remain using $OS for now to avoid a breaking change.
=> Generalized parameters on benchmark imports

CHANGELOG_CISDSCResourceGeneration.md, src/CISDSCResourceGeneration/functions/private/Get-RecommendationFromGPOHash.ps1, test/CISDSCResourceGeneration.Tests.ps1
#182 
- Ignoring a correction is something you have to intentionally configure so it makes more sense to have those be output as debug messages rather than warning.
=> more noise reduction

tools/test_machine_setup.ps1
CISCAT now supports OpenJDK so the setup script has been changed to install that from chocolatey instead of JRE.
=> Changed setup script from jre to openJDK

CHANGELOG.md, src/CISDSC/dscresources/CIS_Microsoft_Windows_10_Enterprise_Release_20H2/CIS_Microsoft_Windows_10_Enterprise_Release_20H2.psd1
_Describe the problem or feature in addition to a link to the issues._ Bump version to indicate Windows 10 20H2 still matches the new version of the benchmark. The resource was regenerated and there was no difference in the information relevant to the project.
_How does this change address the problem?_ The version number is updated to match CIS' documentation.
=> Win10 20h2

CHANGELOG.md, src/CISDSC/docs/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_20H2.md, src/CISDSC/dscresources/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_20H2/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_20H2.psd1, src/CISDSC/dscresources/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_20H2/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_20H2.schema.psm1
_Describe the problem or feature in addition to a link to the issues._ Duplicate keys were discovered when investigating another issue. Resolves #222. 
_How does this change address the problem?_
1) Appreciated the irony of finding two copies of keys being issue 222
2) Regenerated with the latest copy of the benchmark from CIS making sure to remove the DC GPOs from the directory. This resulted in a few new keys as well.
=> Updated Server 2019 20H2 benchmark

CHANGELOG.md, src/CISDSC/CISDSC.psd1
Finalizes all unreleased changes prior to starting on the v3.0 features such as domain controller support.
- Fixed casing on CISDSC examples directory. [Issue 216](https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/216)
- Added IconURI to CISDSC manifest
- CIS_Microsoft_Windows_Server_2019_Member_Server_Release_20H2 updated to latest benchmark release. [Issue 222](https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/222).
- Duplicate keys for next generation windows security in CIS_Microsoft_Windows_Server_2019_Member_Server_Release_20H2 [Issue 222](https://github.com/techservicesillinois/SecOps-Powershell-CISDSC/issues/222).
=> v2.5.1 release

CHANGELOG.md, CHANGELOG_CISDSCResourceGeneration.md, src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_1809.md, src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_1909.md, src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_2004.md, src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_20H2.md, src/CISDSC/docs/CIS_Microsoft_Windows_10_Enterprise_Release_21H1.md, src/CISDSC/docs/CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607.md, src/CISDSC/docs/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_1809.md, src/CISDSC/docs/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_20H2.md, src/CISDSC/examples/CIS_Microsoft_Windows_10_Enterprise_Release_1809_With_LAPS.ps1, src/CISDSC/examples/CIS_Microsoft_Windows_10_Enterprise_Release_1909_With_LAPS.ps1, src/CISDSC/examples/CIS_Microsoft_Windows_10_Enterprise_Release_2004_With_LAPS.ps1, src/CISDSC/examples/CIS_Microsoft_Windows_10_Enterprise_Release_20H2_With_LAPS.ps1, src/CISDSC/examples/CIS_Microsoft_Windows_10_Enterprise_Release_21H1_With_LAPS.ps1, src/CISDSC/examples/CIS_Microsoft_Windows_Server_2016_Member_Server_Release_1607_With_LAPS.ps1, src/CISDSC/examples/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_1809_With_LAPS.ps1, src/CISDSC/examples/CIS_Microsoft_Windows_Server_2019_Member_Server_Release_20H2_With_LAPS.ps1, src/CISDSCResourceGeneration/plasterTemplates/NewOSBenchmarkCompositeResource/example_With_LAPS.ps1.plaster, src/CISDSCResourceGeneration/plasterTemplates/NewOSBenchmarkCompositeResource/resource.documentation.md
- Old LAPS Product ID replaced with new
Note: Prettier also cleaned up a lot of the markdown. Load the richdiff to see that nothing really changed visually
Resolves #261
=> LAPS product ID change

CHANGELOG.md, src/CISDSC/CISDSC.psd1
- Removed 'Ensure Turn on PowerShell Transcription is set to Enabled (2)' and (3). These are subkeys of 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription' (OutputDirectory and EnableInvocationHeader) which are not mentioned by the CIS Benchmark and erroneously included in the GPOKit. Invalid ValueData for the OutputDirectory key was also causing issues with the MOF file in some cases, depending on how it was generated.
=> Release 4.0.1
